Users:
- Name: "vmadmin"
  State: present
  Comment: "automation user, dynamically altered at runtime - dont change"
  Shell: /bin/bash
  Create_Home: yes
  SSH_Key_file: no
  System: yes
  Groups: "sudo, docker"
  Password: "{{ 'password' | password_hash('sha512') }}"
