---
apt:
  emoji: "ğŸ™ƒ"
  commands:
    list: "apt list --installed"
    install: "sudo apt-get install -y "
    update: "sudo apt-get update -y"
    upgrade: "sudo apt-get upgrade -y"
  packages:
    default:
      - terminator
      - openssl
      - sysstat
      - silversearcher-ag
      # this should let you use the a yubikey for auth
      - libpam-yubico
      - finger
      - ssh
      # - nextcloud-desktop
      - screen
      - youtube-dl
      - bash-completion
      # networking
      - iptables
      - gufw
      - net-tools
      # package managers installing package managers... this is terrible.
      - snapd
      - flatpak
      - gnome-software-plugin-flatpak
      # cat images in the terminal :) works in tmux
      - catimg
      # this lets you ls images as thumbnails, which is helpful sometimes
      - imagemagick
      # pretty syntaxhighlighted cat files with git diff support
      - batcat
      # print a very pretty pallete to see all the colors the terminal can render
      - colortest
    gaming:
      - lutris
      - winehq-staging
      - steam
      # to format disks to exFAT; FAT is too thin for modern windows 10 ISOs
      # - exfat-utils

flatpak:
  emoji: "ğŸ«“ "
  commands:
    setup: "sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"
    list: "flatpak list --columns=application"
    install: "sudo flatpak install -y flathub "
  packages:
    default:
      - "org.freedesktop.Platform/x86_64/21.08"
      # youtube alternative
      - io.freetubeapp.FreeTube
      # password manager
      - com.bitwarden.desktop

snap:
  emoji: "ğŸ«° "
  commands:
    list: "snap list"
    install: "sudo snap install "
  packages:
    default:
      - core
      # rss feed reader
      - fluent-reader
      # screen debugger/sharing tool for android
      - scrcpy

# most of this is actually for powerline, my shell prompt
pip3.10:
  emoji: "ğŸ"
  commands:
    list: "pip3.10 list"
    install: "pip3.10 install --upgrade "
  packages:
    default:
      # this is for python development
      - build
      - twine
      - autoimport
      # this is all powerline
      - powerline-status
      - powerline-gitstatus
      - powerline-kubernetes
      # for the internal ip address powerline shell prompt
      - netifaces
      # supposed to work with powerline for spotify info
      - dbus
      # this does some magic with imports when developing
