---
brew:
  emoji: "üç∫"
  commands:
    list: "brew list -1"
    update: "brew update --quiet"
    upgrade: "brew upgrade --quiet"
    install: "brew install "
    cleanup: "brew cleanup"
  # these are essentially just extra git repos to query for installs/updates
  taps:
    macOS:
      - "wez/wezterm"
      - "zegervdv/zathura"
      - "homebrew/cask-fonts"
  packages:
    # these are all for both macOS and Debian
    default:
      # TUI browser
      - w3m
      # this installs rustup which installs cargo and rust
      - rustup
      - wget
      # terminal based web browser
      - lynx
      # screen session + sharing/splitting - replaces tmux :)
      - zellij
      # recording a shell session to share with others
      - asciinema
      # main terminal based text editors
      - vim
      - neovim
      # terminal based email client
      - neomutt
      # fetch your mail locally
      - offlineimap
      # fuzzy search, helps with completion and searching
      - fzf
      # ls replacement written in rust: https://github.com/Peltoche/lsd
      - lsd
      #  A cat(1) clone with syntax highlighting and Git integration.
      - bat
      # pretty formatting and syntax highlighting
      - rich-cli
      # file TUI: https://www.geeksforgeeks.org/ranger-a-cli-file-manager/
      - ranger
      # preview videos in the terminal. commented by default because it is big
      # - ffmpegthumbnailer
      # cat images in the terminal (e.g. img2sixel imagename.png)
      - libsixel
      # for working with images and making lsimg work
      - imagemagick
      # ag command: like grep or ack, but more modern, for searching file text
      - the_silver_searcher
      # diff, but with colors
      - colordiff
      # prettier top
      - htop
      - gotop
      # quick system metrics, typically used as an MOTD
      - fastfetch
      # prettier du/df outputs: https://github.com/muesli/duf
      - duf
      # rainbow text
      - lolcat
      # blocky fonts: https://devhints.io/figlet
      - figlet
      - toilet
      # less: b/c you get new features if you stay up2date, & brew is up2date
      - less
      # steam locamotive
      - sl
      # a cow that says things
      - cowsay
      # revision control system
      - git
      # programming languages and their package managers
      - python@3.11
      - go
      - node
      # linter for YAML
      - yamllint
      # linter for html5
      - tidy-html5
      # mardown rendering
      - pandoc
      # for parsing json via cli
      - jq
      # search stackoverflow e.g. howdoi extend a dictionary in python
      - howdoi
      # get the quick, short text of how to use various commands
      - tealdeer
      # generating SSL certs and random strings
      - openssl@3
      # password management
      - bitwarden-cli
      # anti virus
      - clamav
      # TUI for gpg keys, for the lazy, like me
      - gpg-tui
      # spotify daemon
      - spotifyd
      # spotify TUI
      - spotify-tui
      # github cli
      - gh
      # gitlab cli
      - glab
    # macOS specific stuff. Won't work with LinuxBrew
    macOS:
      # for testing apis and downloading things
      - curl
      # current version of bash :)
      - bash
      # for setup scripts and compiling things (e.g. YouCompleteMe)
      - cmake
      # so that bash completion stuff works
      - "bash-completion@2"
      # zathura is a document viewer
      - zathura
      - zathura-pdf-mupdf
      - "--cask font-mononoki"
      - "--cask font-hack-nerd-font"
      # this lets us resize windows
      - "--cask rectangle"
      # productivity search and command bar: replacing with cerebro soon
      # - "--cask alfred"
      # Default browser
      - "--cask firefox"
      # File server cloud replacement, not ready yet
      # - "--cask nextcloud"
      # Default terminal used by most macOS users, standard
      - "--cask iterm2"
      # wezterm: Rust based terminal the is cross-OS-compatible
      - "--cask wez/wezterm/wezterm"
      # gives us the default gnu/linux sed we all know and love
      - "gnu-sed"
      # remap keys on macOS
      - "--cask karabiner-elements"
      # This should be docker desktop
      - "--cask docker"
      # primary media player
      - "--cask vlc"
      # youtube replacement
      - "--cask freetube"
      # firewall
      - "--cask lulu"
      # password manager
      - "--cask bitwarden"
      # VPN
      - "--cask protonvpn"
      # email
      - "--cask protonmail-bridge"
      # libreoffice is a FOSS office suite that replaces Google Docs/Office365
      - "--cask libreoffice"
    devops:
      # for backups
      - restic
      # terraform for building stuff
      - terraform
      # cli for k8s (kubernetes)
      - kubectl
      # kubectl plugin manager
      - krew
      # terminal based dashbaord for k8s
      - k9s
      # package manager for k8s
      - helm
      # gitops continuous delivery for k8s configs
      - argocd
      # KinD (Kubernetes in Docker), for small k8s clusters for testing
      - kind
      # other useful goodies
      # manage multiple versions of terraform
      # - tfenv
      # Bitnami sealed-secrets cli: encrypt secrets in yaml files for gitops
      # - kubeseal
      # manages multiple helm files
      # - helmfile
      # AWS's CLI
      # "aws-cli"
      # aws credentials switcher
      # "--cask aws-vault"

apt:
  emoji: "üôÉ"
  commands:
    list: "scripts/get_apt_list.sh"
    update: "sudo apt-get update -y"
    upgrade: "sudo apt-get upgrade -y"
    install: "sudo apt-get install -y "
    cleanup: "sudo apt-get autoremove -y"
  packages:
    default:
      - bash-completion
      - curl
      # BEGIN: makes youcompleteme work
      # needed for compiling things, currently specifically gcc-11
      - gcc-11
      - build-essential
      - cmake
      - vim-nox
      - python3-dev
      - mono-complete
      - openjdk-17-jdk
      - openjdk-17-jre
      # END: makes youcompleteme work
      # grep alternative
      - silversearcher-ag
      # this should let you use the a yubikey for auth
      - libpam-yubico
      # vpn
      - wireguard
      # troubleshooting
      - sysstat
      # networking and firewall
      - iptables
      - net-tools
      # package manager
      - snapd
      # print a pretty pallete to see all colors the terminal can render
      - colortest
      # help fix locale issues
      - "locales-all"
    devops:
      - docker-ce
      - docker-ce-cli
      - docker.io
      - containerd.io
      # like top but for GPUs
      - nvtop
    gui:
      # package manager for gui apps
      - flatpak
      # needed for freetube
      - youtube-dl
      # this lets you install flatpak packages via the gui
      - gnome-software-plugin-flatpak
      # gui firewall
      - gufw
      # pdf viewer with themeing
      - zathura
      # commented out till nextcloud is working
      # - nextcloud-desktop
      # libreoffice is a FOSS office suite that replaces Google Docs/Office365
      - libreoffice
      # GUI interface for pulseaudio, so you can disable audio devices
      - pavucontrol
    gaming:
      # helpful for gaming on linux
      - "nvidia-driver-libs:i386"
      - "steam:i386"
      # to format disks to exFAT; FAT is too thin for modern windows 10 ISOs
      # - exfat-utils

flatpak:
  emoji: "ü´ì "
  commands:
    setup: "flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"
    list: "flatpak list --user --columns=application"
    install: "flatpak install --user --app -y "
  packages:
    gui:
      - "org.freedesktop.Platform/x86_64/21.08"
      # password manager
      - com.bitwarden.desktop
      # youtube alternative
      - io.freetubeapp.FreeTube
      - org.wezfurlong.wezterm
    gaming:
      - lutris

snap:
  emoji: "ü´∞ "
  commands:
    upgrade: "sudo snap refresh"
    list: "snap list"
    install: "sudo snap install "
  packages:
    gui:
      - core
      # screen debugger/sharing tool for android
      - scrcpy
      # rss feed reader
      - "fluent-reader --candidate"
      # media player
      - vlc

# most of this is actually for powerline, my shell prompt
pip3.11:
  emoji: "üêç"
  commands:
    list: "pip3.11 list"
    install: "pip3.11 install --upgrade "
  packages:
    default:
      # keep ourselves up to date
      - onboardme
      # powerline: (status line for tmux/BASH)
      - "git+ssh://git@github.com/powerline/powerline"
      - powerline-gitstatus
      - powerline-kubernetes
      # powerline: for the internal ip address prompt segment
      - netifaces
      # powerline: supposed to work spotify info
      - dbus
      # neovim: needed for vim's python3 interface
      - pynvim
      # this is for git pre-commits
      - pre-commit
      # python development: linting/auto-linting
      - ruff
      - flake8
      - pyflakes
      - autoflake
      # python: does some magic with imports when developing
      # - autoimport
      # python: for building and installing packages
      - pip
      - poetry
      - build
      - twine
    macOS:
      # this is for hacking on the iterm2 python api
      - iterm2
    devops:
      # this is a k8s tool to spin up clusters on your local machine
      - smol-k8s-lab
      # need this for python notebooks
      - ipykernel
      # classic python notebooks
      - notebook
      # latest jupyter notebooks
      - jupyterlab
      # notebook-driven development platform
      - nbdev
      # notebooks in the terminal üíö
      - euporie
      # Voil√† turns Jupyter notebooks into standalone web apps
      # - voila
      # this is for markdown notebook docs and such
      - quarto
