Groups:
  - Name: automation
    State: present
  - Name: adm
    State: present
  - Name: cdrom
    State: present
  - Name: sudo
    State: present
  - Name: dip
    State: present
  - Name: plugdev
    State: present
  - Name: lxd
    State: present
  - Name: docker
    State: present
  - Name: steam
    State: present