---
brew:
  emoji: "ğŸº"
  list_cmd: "brew list -1"
  install_cmd: "brew bundle --file={PKG_MNGR_DIR}/brew/"
  default_packages:
    - Brewfile_standard
  linux_packages:
    - Brewfile_linux
  mac_packages:
    - Brewfile_mac
  work_packages:
    - Brewfile_work

apt:
  emoji: "ğŸ«  "
  list_cmd: "apt list --installed"
  install_cmd: "sudo apt-get install -y "
  default_packages:
    - terminator
    - openssl
    - sysstat
    - silversearcher-ag
    - libpam-yubico
    - finger
    - ssh
    - nextcloud-desktop
    - screen
    - youtube-dl
    # this is for remapping capslock to control
    - gnome-tweaks
    - snapd
    - flatpak
    - gnome-software-plugin-flatpak
  gaming_packages:
    - lutris
    - winehq-staging
    - steam
    - ubuntu-driver-460
    # to format disks to exFAT; FAT is too thin for modern windows 10 ISOs
    - exfat-utils

flatpak:
  emoji: "ğŸ«“"
  list_cmd: "flatpak list  --columns=application"
  install_cmd: "sudo flatpak install -y flathub "
  default_packages:
    - "org.freedesktop.Platform/x86_64/21.08"
    - io.freetubeapp.FreeTube
    - com.bitwarden.desktop

snap:
  emoji: "ğŸ«° "
  list_cmd: "snap list"
  install_cmd: "sudo snap install "
  default_packages:
    - core
    - "fluent-reader --candidate"
